# Generated by Django 4.1.1 on 2023-04-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_addpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpost',
            name='user_prof',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='another_model', to='social_app.profile'),
        ),
    ]
