# Generated by Django 4.1.1 on 2023-04-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_addpost_user_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='user_prof',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='another_model', to='social_app.profile'),
        ),
    ]
